/** Exact spelling/abbreviation variants observed in the 2026-09-10 six-book capture.
 * These are participant keys only: league, kickoff, gender/age, product and
 * ambiguity gates still apply. Generic Athletic Club/United FC stay unaliased. */
const observedTeamNames: readonly (readonly string[])[] = [
  ["oulu","ac oulu"],
  ["tps turku","tps"],
  ["gais goteborg","gais"],
  ["talaea el geish","talaea el gaish"],
  ["farul constanta","ssc farul"],
  ["osters","oster","osters if"],
  ["sint truidense","st truiden","sint truidense vv"],
  ["gent","kaa gent"],
  ["aik fotboll","aik"],
  ["scr altach","rheindorf altach"],
  ["genk","krc genk"],
  ["cs universitatea craiova","cs u craiova"],
  ["northern ireland","bac ireland"],
  ["jaro","ff jaro"],
  ["kups kuopio","kups"],
  ["roda jc","roda"],
  ["wolverhampton","wolves"],
  ["kpv kokkola","kpv"],
  ["grasshoppers","grasshopper club zurich"],
  ["oh leuven","oud heverlee leuven"],
  ["rapid vienna","sk rapid wien"],
  ["heart of midlothian","hearts"],
  ["ukraine","ukraina"],
  ["kfum oslo","kfum"],
  ["uniao leiria","ud leiria"],
  ["dinamo bucharest","dinamo bucuresti","dinamo bucuresti 1948"],
  ["sogdiana jizzakh","sogdiana jizak"],
  ["krylia sovetov","krylya sovetov","kryliya sovetov","pfc krylia sovetov"],
  ["hamkam","ham kam"],
  ["zenit saint petersburg","zenit st petersburg"],
  ["ibv vestmannaeyjar","ibv vestmannaeyja"],
  ["vanspor fk","van spor fk","vanspor","van spor"],
  ["moss","moss fk"],
  ["copenhagen","kobenhavn"],
  ["eif ekenas","ekenas idrottsforening"],
  ["mp mikkeli","mikkelin palloilijat"],
  ["los angeles galaxy","la galaxy"],
  ["stade laval","stade lavallois"],
  ["sonnenhof grossaspach","sg sonnenhof grossaspach","sonnenhoff grossaspach"],
  ["polonia warsaw","polonia warszawa"],
  ["bruk bet termalica nieciecza","termalica bb nieciecza"],
  ["gak grazer","grazer ak"],
  ["uc dublin","ucd"],
  ["ols oulu","ols","oulu ols"],
  ["vjs vantaa","vjs"],
  ["sporting lisbon 2","sporting lisboa 2"],
  ["colchester","colcheste"],
  ["istanbulspor as","istanbulspor a s"],
  ["egersunds","egersund ik","egersunds ik"],
  ["acs sepsi osk sfantu gheorghe","acs sepsi osk sfantul gheorghe"],
  ["bani yas","baniyas sports club"],
  ["saint louis city","st louis city"],
  ["central cordoba sde","central cordoba de santiago del estero","central cordoba santiago del estero"],
  ["caen","sm caen","sm caen cbn"],
  ["queen s park","queens park"],
  ["hodd","hodd il"],
  ["suwon samsung bluewings","suwon s bluewings"],
  ["akron tolyatti","akron togliatti","fk akron togliatti"],
  ["fakel voronezh","fakel vorenezh"],
  ["north macedonia","bac macedonia","republic of north macedonia"],
  ["ayr united","ayr"],
  ["dinamo samarkand","dinamo samarqand"],
  ["poland","ba lan"],
  ["dynamo tbilisi","dinamo tbilisi"],
  ["al taawon buraidah","al taawoun buraidah"],
  ["universidad de concepcion","uni de concepcion"],
  ["deportes la serena","dep la serena"],
];

export const observedFootballTeamAliases: ReadonlyMap<string, string> = new Map(
  observedTeamNames.flatMap(([canonical, ...variants]) => variants.map(variant => [variant, canonical!] as const))
);
